export default function Products() {
  return (
    <div>
        <h3 className="font-bold text-2xl md:text-3xl lg:text-4xl text-center bg-red-400">Explore Cutting-Edge Gadgets</h3>
        <div className="grid grid-cols-8">
            {/* sideBar */}
            <div className="col-span-2">

            </div>
            {/* main Content */}
            <div className="col-span-6">
                <div className="grid grid-cols-1 md:grid cols-2 lg:grid-cols-3">
                    Lorem ipsum, dolor sit amet consectetur adipisicing elit. Veniam quos quae tenetur ducimus amet sit officia! Fugiat corporis sed nobis aliquid magni! Totam laudantium dicta quia cumque iusto omnis ratione itaque doloremque ut minima ad qui repellat quis deleniti ipsa vel, quam fugiat obcaecati corrupti asperiores pariatur? Culpa illo quam hic est eum qui amet libero commodi vel. Expedita, est!
                    Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quaerat voluptas labore incidunt dicta ipsa magni recusandae ipsum illo ratione voluptatum nulla reiciendis molestias quis eaque, iure at quae possimus natus nemo libero voluptates blanditiis, sunt tempore beatae! Impedit dolore ab nostrum labore soluta veniam velit officia ipsa dignissimos molestias tempore expedita, repellendus deleniti rerum, cupiditate odit nobis officiis maiores illum.
                    Lorem ipsum, dolor sit amet consectetur adipisicing elit. Veniam quos quae tenetur ducimus amet sit officia! Fugiat corporis sed nobis aliquid magni! Totam laudantium dicta quia cumque iusto omnis ratione itaque doloremque ut minima ad qui repellat quis deleniti ipsa vel, quam fugiat obcaecati corrupti asperiores pariatur? Culpa illo quam hic est eum qui amet libero commodi vel. Expedita, est!
                    Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quaerat voluptas labore incidunt dicta ipsa magni recusandae ipsum illo ratione voluptatum nulla reiciendis molestias quis eaque, iure at quae possimus natus nemo libero voluptates blanditiis, sunt tempore beatae! Impedit dolore ab nostrum labore soluta veniam velit officia ipsa dignissimos molestias tempore expedita, repellendus deleniti rerum, cupiditate odit nobis officiis maiores illum.
                    Lorem ipsum, dolor sit amet consectetur adipisicing elit. Veniam quos quae tenetur ducimus amet sit officia! Fugiat corporis sed nobis aliquid magni! Totam laudantium dicta quia cumque iusto omnis ratione itaque doloremque ut minima ad qui repellat quis deleniti ipsa vel, quam fugiat obcaecati corrupti asperiores pariatur? Culpa illo quam hic est eum qui amet libero commodi vel. Expedita, est!
                    Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quaerat voluptas labore incidunt dicta ipsa magni recusandae ipsum illo ratione voluptatum nulla reiciendis molestias quis eaque, iure at quae possimus natus nemo libero voluptates blanditiis, sunt tempore beatae! Impedit dolore ab nostrum labore soluta veniam velit officia ipsa dignissimos molestias tempore expedita, repellendus deleniti rerum, cupiditate odit nobis officiis maiores illum.
                    Lorem ipsum, dolor sit amet consectetur adipisicing elit. Veniam quos quae tenetur ducimus amet sit officia! Fugiat corporis sed nobis aliquid magni! Totam laudantium dicta quia cumque iusto omnis ratione itaque doloremque ut minima ad qui repellat quis deleniti ipsa vel, quam fugiat obcaecati corrupti asperiores pariatur? Culpa illo quam hic est eum qui amet libero commodi vel. Expedita, est!
                    Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quaerat voluptas labore incidunt dicta ipsa magni recusandae ipsum illo ratione voluptatum nulla reiciendis molestias quis eaque, iure at quae possimus natus nemo libero voluptates blanditiis, sunt tempore beatae! Impedit dolore ab nostrum labore soluta veniam velit officia ipsa dignissimos molestias tempore expedita, repellendus deleniti rerum, cupiditate odit nobis officiis maiores illum.
                    Lorem ipsum, dolor sit amet consectetur adipisicing elit. Veniam quos quae tenetur ducimus amet sit officia! Fugiat corporis sed nobis aliquid magni! Totam laudantium dicta quia cumque iusto omnis ratione itaque doloremque ut minima ad qui repellat quis deleniti ipsa vel, quam fugiat obcaecati corrupti asperiores pariatur? Culpa illo quam hic est eum qui amet libero commodi vel. Expedita, est!
                    Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quaerat voluptas labore incidunt dicta ipsa magni recusandae ipsum illo ratione voluptatum nulla reiciendis molestias quis eaque, iure at quae possimus natus nemo libero voluptates blanditiis, sunt tempore beatae! Impedit dolore ab nostrum labore soluta veniam velit officia ipsa dignissimos molestias tempore expedita, repellendus deleniti rerum, cupiditate odit nobis officiis maiores illum.
                    Lorem ipsum, dolor sit amet consectetur adipisicing elit. Veniam quos quae tenetur ducimus amet sit officia! Fugiat corporis sed nobis aliquid magni! Totam laudantium dicta quia cumque iusto omnis ratione itaque doloremque ut minima ad qui repellat quis deleniti ipsa vel, quam fugiat obcaecati corrupti asperiores pariatur? Culpa illo quam hic est eum qui amet libero commodi vel. Expedita, est!
                    Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quaerat voluptas labore incidunt dicta ipsa magni recusandae ipsum illo ratione voluptatum nulla reiciendis molestias quis eaque, iure at quae possimus natus nemo libero voluptates blanditiis, sunt tempore beatae! Impedit dolore ab nostrum labore soluta veniam velit officia ipsa dignissimos molestias tempore expedita, repellendus deleniti rerum, cupiditate odit nobis officiis maiores illum.
                    Lorem ipsum, dolor sit amet consectetur adipisicing elit. Veniam quos quae tenetur ducimus amet sit officia! Fugiat corporis sed nobis aliquid magni! Totam laudantium dicta quia cumque iusto omnis ratione itaque doloremque ut minima ad qui repellat quis deleniti ipsa vel, quam fugiat obcaecati corrupti asperiores pariatur? Culpa illo quam hic est eum qui amet libero commodi vel. Expedita, est!
                    Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quaerat voluptas labore incidunt dicta ipsa magni recusandae ipsum illo ratione voluptatum nulla reiciendis molestias quis eaque, iure at quae possimus natus nemo libero voluptates blanditiis, sunt tempore beatae! Impedit dolore ab nostrum labore soluta veniam velit officia ipsa dignissimos molestias tempore expedita, repellendus deleniti rerum, cupiditate odit nobis officiis maiores illum.
                    Lorem ipsum, dolor sit amet consectetur adipisicing elit. Veniam quos quae tenetur ducimus amet sit officia! Fugiat corporis sed nobis aliquid magni! Totam laudantium dicta quia cumque iusto omnis ratione itaque doloremque ut minima ad qui repellat quis deleniti ipsa vel, quam fugiat obcaecati corrupti asperiores pariatur? Culpa illo quam hic est eum qui amet libero commodi vel. Expedita, est!
                    Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quaerat voluptas labore incidunt dicta ipsa magni recusandae ipsum illo ratione voluptatum nulla reiciendis molestias quis eaque, iure at quae possimus natus nemo libero voluptates blanditiis, sunt tempore beatae! Impedit dolore ab nostrum labore soluta veniam velit officia ipsa dignissimos molestias tempore expedita, repellendus deleniti rerum, cupiditate odit nobis officiis maiores illum.
                </div>
            </div>
        </div>
    </div>
  )
}
